services:
  db:
    image: postgis/postgis:16-3.4
    container_name: mapaset_db
    environment:
      POSTGRES_DB: mapaset
      POSTGRES_USER: mapaset
      POSTGRES_PASSWORD: mapaset123
    ports:
      - "5433:5432"
    volumes:
      - mapaset_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mapaset -d mapaset"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mapaset_db_data:
